version: "3.8"
services:
  dev-db:
    image: postgres:17
    # platform: linux/amd64 is for windows environment. For linux no need it and it needs to be delete it
    platform: linux/amd64
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - streetbouldertracker
  test-db:
    image:
      postgres:17
      # platform: linux/amd64 is for windows environment. For linux no need it and it needs to be delete it
    platform: linux/amd64
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - streetbouldertracker
networks:
  streetbouldertracker:
